model_family: llava-phi
model_path: ./models/final_ft_10_epochs_lr2e-05_llava-phi_full

LoRA:
  r: 128
  alpha: 256
  dropout: 0.05

lr: 1e-4
split: forget10
data_path: ./dataset/full.json
batch_size: 4
gradient_accumulation_steps: 16
num_epochs: 5
forget_loss: idk
tune_vision_tower: False
tune_mm_projector: True
tune_language_model: True
max_grad_norm: 1.0

save_dir: ${model_path}/${forget_loss}_${lr}_${split}_${num_epochs}
save_steps: 6
overwrite_dir: false
weight_decay: 0.01
save_model: true
eval_while_train: false
eval_only: false
seed: 233
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.06
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""


eval:
  # retain_result: data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [locuslab/TOFU, locuslab/TOFU, locuslab/TOFU, locuslab/TOFU]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 64
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30
  retain_result: null
